### ISSUE TITLE
保存一个GBK文件之后 窗口失焦再获得焦点时 代码折叠会全部展开

### ISSUE THREAD

**Issue by tinymins** [seanliang/ConvertToUTF8#49]
您好 我发现一个用户体验不太舒服的地方：
保存一个GBK文件之后 窗口失焦再获得焦点时 代码折叠会全部展开
建议判断下有没有在外部修改过 没有修改的话就没必要重载文件导致代码折叠全部展开

**Comment by seanliang** [comment]
因为Sublime Text本身不支持GBK，本插件是在其完成UTF8文件保存时在后台对文件进行转码实现的。因为这个转码动作不在Sublime Text的监控范围内，它会认为文件被“外部”修改了，从而强制执行重载。遗憾的是，Sublime Text不支持禁用这种强制重载。类似的功能请求有好几个，不过都还没得到作者响应：
- http://sublimetext.userecho.com/topic/79660-ask-before-file-reload/
- http://sublimetext.userecho.com/topic/122085-add-an-option-to-disable-auto-reloading-of-changed-file/
- http://sublimetext.userecho.com/topic/389968-possibility-to-disable-auto-reload/

我再研究看看有没有办法在重载后恢复折叠状态。

**Comment by tinymins** [comment]
多谢~
想办法重载之后恢复折叠状态是个蛮不错的思路

**Comment by seanliang** [comment]
已在1.2.9版本中实现，请更新并确认。

**Comment by tinymins** [comment]
好强的执行力！非常赞，再次感谢~ XD
