### ISSUE TITLE
保存后不恢复 view 位置

### ISSUE THREAD

**Issue by demon386** [seanliang/ConvertToUTF8#50]
长文件，保存之后 view 到文件头部，cursor 位置是不变的，因为前移一下还会回到原来 view 的地方。是不是保存之后没调用 adjust_view?

**Comment by demon386** [comment]
另外还有保存之后 cursor 错位的问题。

**Comment by seanliang** [comment]
我理解一下你的说法：保存文件后，将cursor移动到其他位置，切换到其他tab，再切换回来时cursor恢复到保存时的位置。对么？

**Comment by demon386** [comment]
不用切换 tab，就同一个文件，用快捷键保存之后即时发生。

**Comment by seanliang** [comment]
我本地测试没发现保存后会发生偏移。麻烦提供一下操作系统、ST版本、自定义的设置及安装过的插件等信息。有可能的话请给些截图说明。
