### ISSUE TITLE
默认保存编码为GBK，convert_on_save为true，保存的时候会闪一下

### ISSUE THREAD

**Issue by FrozenMoon** [seanliang/ConvertToUTF8#57]
sublime 3
插件设置如下：
// Maximum size for encoding cache, 0 means no cache
"max_cache_size" : 0,
// Maximum lines to detect, 0 means unlimited
"max_detect_lines" : 0,
// Convert when previewing file: true or false
"preview_action" : true,
// Encoding for new file, empty means using sublime text's "default_encoding" setting
"default_encoding_on_create" : "GBK",
// Set this option to true will cause Sublime Text reload the saved file when losing focus
"lazy_reload": false,
// Convert in Find Results view
"convert_on_find": true,
// Convert when loading/saving a file
"convert_on_load" : true,
"convert_on_save" : true

然后我把lazy_reload设置成true，在保存就不会闪了，切换出去失去焦点了才会闪，有个朋友的是sublime2，没这个问题。

**Comment by seanliang** [comment]
感谢你的反馈。

本插件在后台转码并保存文件后，ST会认为文件被外部程序修改，从而自动重载文件内容造成乱码，本插件会侦测此事件并恢复回正常状态，此时会出现闪动现象。

但ST2和ST3在重载的时机上有所不同，ST2会在窗口切换时重载，此时用户感受不到闪动，但ST3会立即重载，因而会有明显感受。为此增加的lazy_reload参数，首先将转码后的文件保存在临时目录，在当前文档失去焦点时再做实际覆盖。

**Comment by FrozenMoon** [comment]
感谢您的回复。
又发现一个问题了,具体操作为：
打开一个文本，转成了GBK（配置和上面的一样）:
然后随意输入字符，保存文件，ctrl+r 查找符号，这个时候貌似会重新载入原始文件，而没有发生转换导致当前编辑的文件有乱码，按ctrl+z 撤销操作可以返回之前的状态。

不知道是st还是插件的原因？

**Comment by seanliang** [comment]
@FrozenMoon 乱码的问题请看一下是否与 #55 相似，可能是由其他插件引起。

**Comment by vmarsed** [comment]
这个太糟了...重载后本来收起来的缩进全部展开了....

**Comment by seanliang** [comment]
@vmarsed 没理解你的意思，能详细说明下？
