### ISSUE TITLE
ST3 中 preview_action 选项失效

### ISSUE THREAD

**Issue by ParadiseDS** [seanliang/ConvertToUTF8#58]
在ST2中如果该选项为false则预览文件时不会转码，直至为其打开一个tab
ST3中如果碰到需要转码的文件，无论该选项设置为true或False，都无法进入preview模式，在sidebar中单击文件就会打开一个新tab并且自动转码
主要用于对编码的检查，因为有时候会漏过status bar里的信息。。preview如果出现乱码能比较清楚地发现问题
PS: Goto Anything中这个选项似乎还是可以用的。。

**Comment by seanliang** [comment]
ST3的预览行为与ST2不同，会打开一个tab view，而且目前的API无法将这个tab与其他正常的tab区分开，因此该选项暂时对ST3不起作用。如果我找到确实可行的办法再做更新。

See: https://github.com/seanliang/ConvertToUTF8/issues/16#issuecomment-15580799
