### ISSUE TITLE
 win10 ST3 chinese title show error&show large and small

### ISSUE THREAD

**Issue by decemer** [seanliang/ConvertToUTF8#60]
![360 16230321105112153](https://cloud.githubusercontent.com/assets/6077595/11898013/60ad0b30-a5cf-11e5-929c-f537b24e1bf5.png)
font=微软雅黑
 win10 ST3 chinese title show error&show large and small
标题显示方块
有些字体有些会向上偏移一点，没有对齐

**Comment by seanliang** [comment]
标题乱码请参考帮助文档，设置dpi_scale参数：https://github.com/seanliang/ConvertToUTF8/blob/master/README.zh_CN.md#注意

内容不对齐，本地无法重现。不过与本地微软雅黑字体比对，截图的字体不太像简体中文版的微软雅黑。特别明显的是：“系”字上部是撇横而不是撇折，“小”字底有竖钩；”师“左侧是一竖而不是一点。

**Comment by decemer** [comment]
谢谢thx!
第二个问题,您的意思是换字体"如宋体"就能解决solved 是吧
