### ISSUE TITLE
How to keep "illegal multibyte sequence" (wrong encode character) when save

### ISSUE THREAD

**Issue by quyen194** [seanliang/ConvertToUTF8#62]
Dear seanliang,

I have a source file with SJIS encoding, it has some wrong encode character (when saving file, ConvertToUTF8 said: illegal multibyte sequence). And ConvertToUTF8 will remove it from source. How to keep them when save?
I tried sakura editor and it did keep, but i love sublime text.

Thanks and best regards,

**Comment by seanliang** [comment]
This plugin is written in Python which API can not meet your requirement. The write method will fail completely if there is any malformed data. That's the reason why I have to ignore those data.

**Comment by quyen194** [comment]
Thanks
If i can improve it, I will create a pull request ^^

Best regards

**Comment by seanliang** [comment]
@quyen194 That would be great. :+1:
