### ISSUE TITLE
For Cuda

### ISSUE THREAD

**Issue by Alexey-T** [seanliang/ConvertToUTF8#64]
Hi; Maybe possible to do this encoding/decoding,   for Cudatext [uvviewsoft.com]?

**Comment by seanliang** [comment]
I just download CudaText and have a try. It seems it has native support for CJK encodings (at which this plugin aims) via "Reload as" menu items. I might be able to create a plugin for encoding detecting, but I can't find any API to invoke SetFrameEncoding method.

**Comment by Alexey-T** [comment]
from Asian it has support for - 6 codepages. Are they all, others no need?

Api: the way to support enc, maybe is to handle on_open, then in on_open convert text to Unicode, then call ed.set_text_all(text).... and handle on_save: do saving.

**Comment by seanliang** [comment]
There are different encodings and variants for each language. For example, there are different encodings for Japanese: SHIFT-JIS, EUC-JP, CP932, ISO-2022-JP.

"Only encodings supported by LConvEncoding are shown." Do you mean [this](https://github.com/alrieckert/lazarus/blob/master/components/lazutils/lconvencoding.pas)? There are "DBCSToUTF8" and "UTF8ToDBCS" methods, but I can't find their implementation. Not sure whether it supports all DBCS encodings or not.

The way you mentioned is just the way this plugin does, but it is inefficient. Native support is better. :laughing:

**Comment by Alexey-T** [comment]
DBCStoUtf8 can only do this-

~~~
      case CodeP of
        936:
          code := Uni936C[SearchTable(CP936CC, code)];
        950:
          code := Uni950C[SearchTable(CP950CC, code)];
        949:
          code := Uni949C[SearchTable(CP949CC, code)];
        932:
          code := Uni932C[SearchTable(CP932CC, code)];
        else
          code := 0;
      end;
~~~
so it is same encodings. so I cannot support more in native code..

**Comment by seanliang** [comment]
I've created another repository for CudaText: https://github.com/seanliang/ConvertToUTF8ForCudaText.

Will create another issue there for further discussion.

**Comment by Alexey-T** [comment]
Posted some issues at https://github.com/seanliang/ConvertToUTF8ForCudaText
