### ISSUE TITLE
Can not convert file encoding of to GBK, it was saved as UTF-8 instead

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [seanliang/ConvertToUTF8#70]
```
Can not convert file encoding of test.txt to GBK, it was saved as UTF-8 instead:
'gbk' codec can't encode character '\xa5' in position 226: illegal multibyte sequence
```

Warning when I try to save a modified file (Chinese characters added)

**Comment by seanliang** [comment]
Could you attach the saved file for investigation?

**Comment by jkldgoefgkljefogeg** [comment]
How can I find the "position x"? The file is rather large.

**Comment by seanliang** [comment]
Position starts with 0, and every character including control characters (tab, new line, etc) is counted.

BTW, `\xa5` represents for Unicode `¥` sign, which is not supported by GBK. You can use `￥` as an  alternative, its code is `\uFFE5`.

Hope this helps.

**Comment by jkldgoefgkljefogeg** [comment]
The issue seems to be caused by` '` somehow replaced by `¡¯`.

Is there a way to jump to position x?

**Comment by seanliang** [comment]
You can use `Goto Anything` (<kbd>Ctrl</kbd> + <kbd>P</kbd>) and type `::226` in the panel to jump to position 226.
