### ISSUE TITLE
Remove the file encoding display on the status bar

### ISSUE THREAD

**Issue by evandrocoan** [seanliang/ConvertToUTF8#71]
### Add option or just to remove the file encoding display on the status bar

![image](https://cloud.githubusercontent.com/assets/5332158/20124599/be77be6e-a60e-11e6-90aa-2e6768c4c75a.png)

If is annoying as on Sublime Text 3, it is already showed.

![image](https://cloud.githubusercontent.com/assets/5332158/20124604/c99257aa-a60e-11e6-860b-aad59ba807ec.png)

**Comment by seanliang** [comment]
@evandrocoan Do you mean you want to hide the encoding that ConvertToUTF8 shows?

In the cases which ConvertToUTF8 comes to play, the encoding ST3 shows is incorrect, it might be misleading the users if the encoding is removed.

As I know, ST3's default value of `show_encoding` option is false, so you might want to keep it false.

**Comment by evandrocoan** [comment]
@seanliang first, thank for supporting this package. I did not know the default encoding could be hidden. I am disabling it and letting this package shows it.
