### ISSUE TITLE
Fallback encoding

### ISSUE THREAD

**Issue by trandaihung** [seanliang/ConvertToUTF8#73]
It seems that ConvertToUTF8 asks for encoding whenever I open a document because it cannot detect the encoding with 100% confidence. It is very frustrating as I have to manually choose encoding everytime.

Do we have this setting or I just missed something? Sorry, I couldn't find detailed documents about this package.

**Comment by seanliang** [comment]
Please set the `convert_on_load` to `false` in your User Settings (via `Preference > Package Settings > ConvertToUTF8 > Settings - User`). Check https://github.com/seanliang/ConvertToUTF8 for more details.

**Comment by trandaihung** [comment]
@seanliang Thanks for your response. It seems the only way now.
