### ISSUE TITLE
An annoying prompt on saving when "always_prompt_for_file_reload" is true

### ISSUE THREAD

**Issue by taroxd** [seanliang/ConvertToUTF8#76]
![image](https://cloud.githubusercontent.com/assets/6070540/26817555/a64c2810-4ac9-11e7-8eb5-52859d69b443.png)
As is shown in the screenshot, each time the file with GBK/Shift-JIS encoding is saved, I will always be prompted for a file reload. This is pretty annoying.

**Comment by seanliang** [comment]
You can try to set the `lazy_reload` of ConvertToUTF8 to `true`. See https://github.com/seanliang/ConvertToUTF8#configuration for more information.

**Comment by taroxd** [comment]
Thanks.
