### ISSUE TITLE
UTF8 with BOM 编码文件在保存时会自动转换成UTF8文件

### ISSUE THREAD

**Issue by michaelHL** [seanliang/ConvertToUTF8#84]
虽然 UTF8 with BOM 编码不大受待见，但有些程序还必须用上这编码（比如 AutoHotKey），但如题，with BOM 的编码文件在保存时会自动转成 without BOM 的格式，AutoHotKey 就不识别了，`ConvertToUTF8` 插件设置中几个 `convert_on_*` 为 `False` 均无效，望解决！

**Comment by seanliang** [comment]
你好，本插件是不会对BOM文件有任何动作的，我再三尝试，也没复现你说的问题。能麻烦提供文件样本及复现过程么？

**Comment by michaelHL** [comment]
@seanliang 你好，我也试着复现当时的情景，但无法复现，可能当时是其他原因所致。

当时因为编译的 AutoHotKey 脚本里面含有中文所以文件格式需为 UTF8 with BOM，但现在看来即甚至回滚上次的修改，也可以正常工作，比较奇怪。
