### ISSUE TITLE
Error: Codecs missing

### ISSUE THREAD

**Issue by sprite-1** [seanliang/ConvertToUTF8#93]
I already installed the [linked package](https://github.com/seanliang/Codecs33/tree/linux-x64) from Package Control but this error still shows up. I'm on elementaryOS 5.0 (based on Ubuntu 18.04 LTS)

What could be the problem here?

**Comment by seanliang** [comment]
Could you please post the console log(<kbd>CTRL</kbd>+<kbd>`</kbd>) log?

**Comment by sprite-1** [comment]
[Okay, here's the log on the console](https://gist.github.com/sprite-1/d79771fe41396e49b620ff8dc39c6f8c)

**Comment by seanliang** [comment]
It seems both ConvertToUTF8 and Codecs33 are loaded. Can't you view the files encoded in SHIFT_JIS? A sample text file and a screenshot would help.

**Comment by sprite-1** [comment]
Sure thing

![image](https://user-images.githubusercontent.com/33685433/51685688-cf966a00-2029-11e9-8d65-1f27ba0d20cf.png)

Here's the text file. I hope GitHub doesn't change encoding on upload

[jptest.txt](https://github.com/seanliang/ConvertToUTF8/files/2792168/jptest.txt)

**Comment by seanliang** [comment]
I have a try, but it seems everything works. Do you install any other plugins? If so, please disable them temporary and try again. Or start with a fresh installation.
![eleos](https://user-images.githubusercontent.com/1852862/51727791-95b87880-20a8-11e9-9a86-a6296c480547.jpg)

**Comment by sprite-1** [comment]
Weird, I completely started over fresh and it still won't load with both Codecs33 and ConvertToUTF8 installed

![image](https://user-images.githubusercontent.com/33685433/51728332-d9ac7d00-20aa-11e9-8874-16194ce29037.png)

Are you using the latest [devbuild](https://www.sublimetext.com/3dev)?

**Comment by seanliang** [comment]
Nope, I'm using [the stable channel](https://www.sublimetext.com/docs/3/linux_repositories.html#apt). Both plugins were installed manually, the screenshot of `Packages` folder:
![folders](https://user-images.githubusercontent.com/1852862/51734889-d6bc8700-20c0-11e9-8f40-da104d45439d.png)

Type `sublime.version(), sublime.platform(), sublime.arch(), sublime.sys.path` in the console, the output should be something like this:
> ('3176', 'linux', 'x64', ['/opt/sublime_text', '/opt/sublime_text/python3.3.zip', '/home/sean/.config/sublime-text-3/Lib/python3.3', '/home/sean/.config/sublime-text-3/Packages', '/home/sean/.config/sublime-text-3/Packages/Codecs33/lib'])

**Comment by sprite-1** [comment]
We're pretty much the same in folder structure and console output aside from the sublime text version so this is really weird 🙁

![image](https://user-images.githubusercontent.com/33685433/51735478-81817500-20c2-11e9-9346-3c534272ae09.png)

> ('3188', 'linux', 'x64', ['/opt/sublime_text', '/opt/sublime_text/python3.3.zip', '/home/sprite-1/.config/sublime-text-3/Lib/python3.3', '/home/sprite-1/.config/sublime-text-3/Packages', '/home/sprite-1/.config/sublime-text-3/Packages/Codecs33/lib'])

I checked the changelog and this is the only thing that had anything related to encoding in general between your version and mine

![image](https://user-images.githubusercontent.com/33685433/51735902-98749700-20c3-11e9-8b3d-69fd1df0ea19.png)

**Comment by seanliang** [comment]
Ok, I got the error information. Will check it later.
> Codecs33/lib/_multibytecodec.so: undefined symbol: PyExc_ValueError

**Comment by seanliang** [comment]
@sprite-1 @beyond2002
Sublime Text team will fix this problem in next build as [Will said](https://forum.sublimetext.com/t/plugin-codecs33-broken-since-3178/41826/2?u=seanliang).

**Comment by sprite-1** [comment]
That's awesome to hear! Can't wait to try it out!

**Comment by sprite-1** [comment]
Confirmed working in build 3190!

![image](https://user-images.githubusercontent.com/33685433/53000168-b9ca6800-3462-11e9-8ae5-225500f2366b.png)

**Comment by seanliang** [comment]
Thanks for reporting the problem.
